name: Exercice 2

on: 
  workflow_dispatch:

env:
  a: 1 
  b: 2

jobs:
  job1:
    if: ${{ vars.A > 0 && vars.B > 0 }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: a et b sont positive 
      run: echo "les vars sont positives"
  # job2:
  #   if: ${{ success() }}
  #   runs-on : ubuntu-latest
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v2
  #   - name: Si echec
  #     run: echo "Le JOB1 a echoué"