name: Exercice 2

on: 
  workflow_dispatch:

env:
  a: 1
  b: 2


jobs:
  job1:
    if: a>0 && b>0
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: a et b sont positive 
      run: echo $a " et " $b " et > à 0" 
  # job2:
  #   if: ${{ success() }}
  #   runs-on : ubuntu-latest
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v2
  #   - name: Si echec
  #     run: echo "Le JOB1 a echoué"